# Generated by Django 3.0.7 on 2020-07-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oyuuser',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, unique=True), unique=True),
        ),
    ]
