# Generated by Django 3.0.7 on 2020-07-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_oyuuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oyuuser',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
