# Generated by Django 3.0.7 on 2020-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200701_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oyuuser',
            name='image_file',
            field=models.CharField(default='default.png', max_length=100),
        ),
    ]
