# Generated by Django 3.0.7 on 2020-07-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200715_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtfChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('category', models.CharField(choices=[('miscellaneous', 'misc'), ('cryptography', 'crypto'), ('forensics', 'forensics'), ('reverse engineering', 're')], max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=100)),
                ('solved_users_count', models.IntegerField()),
            ],
        ),
    ]
