# Generated by Django 3.0.7 on 2020-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_ctfchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfchallenge',
            name='solved_users_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctfchallenge',
            name='state',
            field=models.CharField(default='active', max_length=100, null=True),
        ),
    ]
