# Generated by Django 3.0.7 on 2020-07-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200717_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfchallenge',
            name='category',
            field=models.CharField(choices=[('miscellaneous', 'misc'), ('cryptography', 'crypto'), ('forensics', 'forensics'), ('reverse engineering', 're'), ('web exploitation', 'web'), ('binary exploitation', 'pwn')], max_length=100, null=True),
        ),
    ]
