# Generated by Django 3.0.7 on 2020-07-18 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200717_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='OyuUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Бүтэн нэр')),
                ('region', models.CharField(blank=True, help_text='Сургууль эсвэл ажилладаг газар.', max_length=100, null=True, verbose_name='Харьяа')),
                ('respected', models.PositiveIntegerField(default=0, verbose_name='Хүндлэгдсэн')),
                ('solved_problem', models.PositiveIntegerField(default=0, verbose_name='Бодсон бодлогын тоо')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Цуглуулсан оноо')),
                ('badge_type', models.CharField(choices=[('normal', 'Энгийн'), ('admin', 'Админ'), ('sponser', 'Ивээн тэтгэгч')], default='normal', max_length=50, verbose_name='Цол')),
                ('first_blood', models.PositiveIntegerField(default=0, verbose_name='Түрүүлж бодсон')),
                ('accepted_problem', models.PositiveIntegerField(default=0, verbose_name='Оруулсан бодлогын тоо')),
                ('facebook_link', models.CharField(blank=True, max_length=128, null=True, verbose_name='Facebook link')),
                ('insta_link', models.CharField(blank=True, max_length=128, null=True, verbose_name='Insta link')),
                ('github_link', models.CharField(blank=True, max_length=128, null=True, verbose_name='Github link')),
                ('background_link', models.CharField(default='default.svg', max_length=128, verbose_name='Background Img link')),
                ('avatar_link', models.CharField(default='default.png', max_length=128, verbose_name='Avatar Img link')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('oyu_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Oyu User')),
            ],
        ),
    ]
