USER_TYPE_NORMAL = "normal"
USER_TYPE_ADMIN = "admin"

USER_TYPE_CHOICES = (
    (USER_TYPE_NORMAL, "энгийн"),
    (USER_TYPE_ADMIN, "админ"),
)


CTF_CHALLENGE_CATEGORY_MISCELLANEOUS = 'miscellaneous'
CTF_CHALLENGE_CATEGORY_CRYPTOGRAPHY = 'cryptography'
CTF_CHALLENGE_CATEGORY_FORENSICS = 'forensics'
CTF_CHALLENGE_CATEGORY_REVERSE_ENGINEERING = 'reverse engineering'
CTF_CHALLENGE_CATEGORY_WEB_EXPLOITATION = 'web exploitation'
CTF_CHALLENGE_CATEGORY_BINARY_EXPLOITATION = 'binary exploitation'

CTF_CHALLENGE_CATEGORY_CHOICES = (
    (CTF_CHALLENGE_CATEGORY_MISCELLANEOUS, 'misc'),
    (CTF_CHALLENGE_CATEGORY_CRYPTOGRAPHY, 'crypto'),
    (CTF_CHALLENGE_CATEGORY_FORENSICS, 'forensics'),
    (CTF_CHALLENGE_CATEGORY_REVERSE_ENGINEERING, 're'),
    (CTF_CHALLENGE_CATEGORY_WEB_EXPLOITATION, 'web'),
    (CTF_CHALLENGE_CATEGORY_BINARY_EXPLOITATION, 'pwn')
)


USER_BADGE_TYPE_NORMAL = "normal"
USER_BADGE_TYPE_ADMIN = "admin"
USER_BADGE_TYPE_SPONSER = "sponser"

USER_BADGE_TYPE_CHOICES = (
    (USER_BADGE_TYPE_NORMAL, "Энгийн"),
    (USER_BADGE_TYPE_ADMIN, "Админ"),
    (USER_BADGE_TYPE_SPONSER, "Ивээн тэтгэгч"),
)

USER_REGION_MUST = "must"
USER_REGION_MUST_SICT = "must-sict"
USER_REGION_NUM = "num"
USER_REGION_STUDENT = "student"
USER_REGION_EMPLOYEE = "employee"

USER_REGION_CHOICES = (
    (USER_REGION_MUST, "ШУТИС"),
    (USER_REGION_MUST_SICT, "ШУТИС-МХТС"),
    (USER_REGION_NUM, "МУИС"),
    (USER_REGION_STUDENT, "Сурагч"),
    (USER_REGION_EMPLOYEE, "Ажилчин"),
)


USER_CHALLENGE_STATUS_SOLVED = "solved"
USER_CHALLENGE_STATUS_ATTEMPTED = "attempted"

USER_CHALLENGE_STATUS_CHOICES = (
    (USER_CHALLENGE_STATUS_SOLVED, "Бодсон"),
    (USER_CHALLENGE_STATUS_ATTEMPTED, "Оролдло хийсэн"),
)


BACKGROUND_IMG_DEFAULT = "img/users/background/default.svg"
AVATAR_IMG_DEFAULT = "img/users/avatar/default.png"
